language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*" PHPUNIT_BRIDGE=true

matrix:
  include:
    - php: 5.3.3
      env: USE_DEPS="lowest"
    - php: 5.5
      env: SYMFONY_VERSION="2.4.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.5.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.6.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - php: 5.5
      env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="2.8.*" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
    - env: SYMFONY_VERSION="dev-master" PHPUNIT_BRIDGE=true MIN_STABILITY="dev"
  fast_finish: true

install:
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - sh travis_install_dependencies.sh

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;

notifications:
  email:
    on_success: always
    on_failure: always

# use container-based infrastructure
sudo: false

# cache Composer's package cache
cache:
  directories:
    - $HOME/.composer/cache
